apiVersion: v1
kind: Secret
metadata:
  namespace: openshift-config
  name: htpass-secret
data:
  htpasswd: dXNlcjokMnkkMDUkMmk1dDVFSEdHelgxOGQ0MFVCMXREZW5EajFkU0g1NjhiUGFRdnBaZVpWSVBKaWhpNlI5eVMKZGV2ZWxvcGVyOiQyeSQwNSR4RnlSVDQyNnduZ2U1eDgzR0MvLnplZXo3YllwMXN3T25BMGlOZlByZC9yLk9zTkMzQ3lHSwpvcGVyYXRvcjokMnkkMDUkQnguMXppaWcuY1dXMzFCZ2pYTUlZLlhRSFcvUEdNZ3pyWHRGWWlVUnBrWFNEc2xpRWZGbjYKc2VjdXJpdHk6JDJ5JDA1JEp3RmhySlRvdmF0WEJCTVc0REh2VE9XbldINjNxRXlYZndPT0JnWS9rSTR1WWhwMHVSZXJHCmFkbWluOiQyeSQwNSRaa1EydTVna294UmJpTVZTUDA5MGJPVFE2NXg0dzJmNEtOQmRhRmd2dFBDYktzdkVwN25jZQo=


